In [1]:
import tensorflow as tf
import numpy as np
x=np.arange(0,100,4)
x.reshape(5,5).T
y=tf.nn.sigmoid(x.astype("float32"))


ImportError: No module named tensorflow

In [2]:
s=tf.Session()

NameError: name 'tf' is not defined

In [2]:
import numpy as np
import os
#import train
def load_mnist():
    data_dir = '../data'
    fd = open(os.path.join(data_dir, 'train-images-idx3-ubyte'))
    loaded = np.fromfile(file=fd, dtype=np.uint8)
    trX = loaded[16:].reshape((60000, 28, 28, 1)).astype(np.float)

    fd = open(os.path.join(data_dir, 'train-labels-idx1-ubyte'))
    loaded = np.fromfile(file=fd, dtype=np.uint8)
    trY = loaded[8:].reshape((60000)).astype(np.int)

    fd = open(os.path.join(data_dir, 't10k-images-idx3-ubyte'))
    loaded = np.fromfile(file=fd, dtype=np.uint8)
    teX = loaded[16:].reshape((10000, 28, 28, 1)).astype(np.float)

    fd = open(os.path.join(data_dir, 't10k-labels-idx1-ubyte'))
    loaded = np.fromfile(file=fd, dtype=np.uint8)
    teY = loaded[8:].reshape((10000)).astype(np.int)

    trY = np.asarray(trY)
    teY = np.asarray(teY)

    perm = np.random.permutation(trY.shape[0])
    trX = trX[perm]
    trY = trY[perm]

    perm = np.random.permutation(teY.shape[0])
    teX = teX[perm]
    teY = teY[perm]

    return trX, trY, teX, teY


def print_digit(digit_pixels, label='?'):
    for i in range(28):
        for j in range(28):
            if digit_pixels[i, j] > 128:
                print '#',
            else:
                print '.',
        print ''

    print 'Label: ', label


def main():
    trainX, trainY, testX, testY = load_mnist()
    print "Shapes: ", trainX.shape, trainY.shape, testX.shape, testY.shape
    print "\nDigit sample"
    print_digit(trainX[2], trainY[2])
    train.train(trainX, trainY)
    labels = train.test(testX)
    accuracy = np.mean((labels == testY)) * 100.0
    print "\nTest accuracy: %lf%%" % accuracy

main()

Shapes:  (60000L, 28L, 28L, 1L) (60000L,) (10000L, 28L, 28L, 1L) (10000L,)

Digit sample
. . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . # # # # . . . . . . . 
. . . . . . . . . . # # # # # # # # # # . . . . . . . . 
. . . . . . . . # # # # # # # # # # # . . . . . . . . . 
. . . . . . . . # # # # # # # . . . . . . . . . . . . . 
. . . . . . . . # # # . . . . . . . . . . . . . . . . . 
. . . . . . . . # # # . . . . # # # # . . . . . . . . . 
. . . . . . . . # # # # # # # # # # # # # . . . . . . . 
. . . . . . . . # # # # # # # # # # # # # # . . . . . . 
. . . . . . . . # # # # # . . . . . . # # # # . . . . . 
. . . . . . . . # # . . . . . . . . . . # # # . . . . . 
. . . . . . . . . . . . . . . . . . . . # # # . . . . . 

NameError: global name 'train' is not defined

In [12]:
trainX, trainY, testX, testY = load_mnist()
tx=trainX.reshape(60000,784)
w=np.zeros((784,10))
b=np.zeros((1,10))
y=np.dot(tx,w)+b
def sigmoid(x):
    return 1/(1+np.exp(-x))
def softmax(x):
    return np.exp(x)/(np.sum(np.exp(x),axis=1,keepdims=True))
def cross_entropy(target,predicted):
    #print(np.log(y1))
    return (-np.sum(target*np.log(predicted)))/60000
ty=np.zeros((60000,10))
ty[np.arange(60000),trainY] = 1
#ty=ty.reshape((60000,1,10))
z=softmax(y)
error=cross_entropy(ty,z)
for i in range(10):
    #print tx.shape,w.shape
    y=np.dot(tx,w)+b
    print(y[0])
    soft=softmax(y)
    loss=cross_entropy(ty,soft)
    print loss
    eta=0.01/60000000
    #print eta
    w=w-eta*(tx.T.dot(soft-ty))
    #print w[1:200]
    b=b-np.around((np.sum(soft-ty)),4)
    print b
newy=testX.reshape(10000,784).dot(w)+b
newys=softmax(newy)
out=newys.argmax(axis=1)
acc=np.sum(out==testY)
print acc

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
2.30258509299
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[ 0.58503993 -0.8559579   0.27755041  0.06235175  0.07833863 -0.16389847
 -0.08244678 -0.32141689  0.29870113  0.12173818]
1.71980882209
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[-0.13275874 -0.77377483  0.36058306 -0.23455142  0.57333488  0.330668
 -0.16089801 -0.26930291 -0.04483206  0.35153203]
1.38750580266
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[ 0.87769134 -1.334812    0.5103555  -0.17459552  0.35015127 -0.01392266
 -0.44544655 -0.74911921  0.66303406  0.31666378]
1.19298195286
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[-0.25261746 -1.33387594  0.75823076 -0.34682051  0.88062509  0.76300726
 -0.22231067 -0.54325804 -0.27479822  0.57181772]
1.08675929387
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[ 0.81687644 -1.62250838  0.58444063 -0.46790634  0.6295222  -0.03713805
 -0.70116231 -0.87594276  1.09229859  0.58151997]
0.994484293423
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [8]:
y=np.dot(tx,w)+b
print(y[0])
soft=softmax(y)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


(60000L, 10L)

In [156]:
d=diff.astype('int64').sum()

In [157]:
d

0

In [127]:
sum1

51.000000000406729

In [72]:
out[1:20]

array([4, 2, 7, 2, 4, 3, 9, 7, 5, 8, 7, 1, 7, 2, 1, 7, 9, 3, 0], dtype=int64)

In [73]:
newys[1]

array([  6.98009930e-03,   2.45136051e-05,   7.20399940e-04,
         1.84179957e-04,   8.31186089e-01,   1.30591550e-02,
         1.08743039e-02,   4.83304000e-03,   5.04713193e-03,
         1.27091087e-01])

In [75]:
acc

8843

In [47]:
newys[100]

array([ 0.01601707,  0.46581554,  0.08537179,  0.08673882,  0.03583715,
        0.04510497,  0.01447139,  0.02631069,  0.1953607 ,  0.02897187])

In [44]:
testY[100]

1

In [16]:
tx.T.dot(z-ty)[40]

array([  792.1,  1045.1,   651.1,  1045.1,  1045.1,  1045.1, -8758.9,
        1045.1,  1045.1,  1045.1])

In [20]:
val=tx.T.dot(z-ty)

In [21]:
w=w-val

In [22]:
y1=np.dot(tx,w)+b

In [25]:
y1[0]

array([  8.19679885e+09,  -7.65717144e+09,   1.57393459e+09,
         2.41269614e+09,  -2.29650121e+09,  -1.29651250e+09,
         2.94495485e+09,  -3.51724581e+09,   1.69385601e+09,
        -2.05480948e+09])

In [180]:
np.set_printoptions(threshold='nan')

In [147]:
y=np.dot(tx,w)

C:\Users\Mr\Anaconda3\envs\py27\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: overflow encountered in exp
C:\Users\Mr\Anaconda3\envs\py27\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: invalid value encountered in divide
C:\Users\Mr\Anaconda3\envs\py27\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: divide by zero encountered in log
C:\Users\Mr\Anaconda3\envs\py27\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: invalid value encountered in multiply


nan
[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]
nan
[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]
nan
[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]
nan
[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]
nan
[[ nan  nan  nan ...,  nan  nan  nan

builtin_function_or_method

In [14]:
import numpy as np
def train(trainX, trainY):
    '''
    Complete this function.
    '''
def test(testX):
    '''
    Complete this function.
    This function must read the weight files and
    return the predicted labels.
    The returned object must be a 1-dimensional numpy array of
    length equal to the number of examples. The i-th element
    of the array should contain the label of the i-th test
    example.
    '''

    return np.zeros(testX.shape[0])